#!/bin/sh

set -e

case "${1}" in
	configure)
		if [ -z "$2" ] || dpkg --compare-versions -- "$2" le-nl "20240822-1~"; then
			# use udevadm to start macsmc-battery-charge-control-end-threshold.path
			# on new installs or upgrades from versions prior to 20240822-1
			if which udevadm >/dev/null 2>&1; then
				udevadm trigger --action=change --subsystem-match=power_supply || true
			fi
		fi
		if which update-initramfs >/dev/null 2>&1; then
			update-initramfs -u -k all
		fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac


#DEBHELPER#

exit 0
